#!/bin/bash
start() {
  port=4443
  for i in $@; do
    echo -e "--> start \e[36m$i\e[0m on port \e[35m$port\e[0m"
    docker run -e ssl=$i -p $port:443 -d ssldummy
    ((port++))
  done
  test $# -eq 0 && start ssl2 ssl3 ssl23 tls1 tls11 tls12
}

stop() {
  echo "--> stop containers"
  docker kill $(docker ps -f ancestor=ssldummy -q --no-trunc)
  echo "--> remove containers"
  docker rm $(docker ps -a -f ancestor=ssldummy -q --no-trunc)
  echo "--> done"
}

cmd=$1
shift
case $cmd in
  start)
    start $@
    ;;
  stop)
    stop 
    ;;
  *)
    echo "Unknown command $cmd, try start or stop"
    exit 1
esac

